FROM postgres:17.4

RUN apt-get update && \
    apt-get install -y --no-install-recommends postgresql-plpython3-17=17.4-1.pgdg120+2 && \
    rm -rf /var/lib/apt/lists/*

COPY create_extension_plpython.sql /docker-entrypoint-initdb.d
COPY ppm_to_regex_function.sql /docker-entrypoint-initdb.d
