services:
  colombus_ui:
      build: ./ui
      ports:
        - "5173:5173"
      networks:
        - colombus-dev_network
      volumes:
        - ./ui/:/app:rw
      environment:
        VITE_API_HOST: "http://localhost"
        VITE_API_PORT: 8180
        VITE_INTERFACE_MODE: "full"
        VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      depends_on:
        - colombus_app
  colombus_app:
    build: .
    ports:
      - "8180:8180"
    networks:
      - colombus-dev_network
    volumes:
      - ./app:/colombus-builder/app:rw
    environment:
      APP_HOST: "http://localhost"
      APP_PORT: 8180
      UI_HOST: "http://localhost"
      UI_PORT: 5173
      DATABASE_URL: postgresql+psycopg://christopher:pinta@colombus_postgresql:5432/colombusdb
      ML_PROFILER_API_URL_PREFIX: "http://mlprofiler_api:8081"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: curl -f http://localhost:8180/health || exit 1
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 20s
    depends_on:
      colombus_postgresql:
        condition: service_healthy
  colombus_postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: christopher
      POSTGRES_PASSWORD: pinta
      POSTGRES_DB: colombusdb
    ports:
      - 5433:5432
    networks:
      - colombus-dev_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "christopher", "-d", "colombusdb"]
      timeout: 10s
      retries: 10
  colombus_pgadmin:
    image: 'dpage/pgadmin4:latest'
    ports:
      - "5051:80"
    networks:
      - colombus-dev_network
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    depends_on:
      colombus_postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s
    profiles:
      - pgadmin

networks:
  colombus-dev_network:
    external: true

volumes:
  postgres_data:
