import { test, expect } from '@playwright/test';

/**
 * Basic Playwright example tests (often generated by default).
 * Used as a sanity check to ensure the testing environment and browser are working.
 */
test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

/**
 * Checks if the "Get started" link on the Playwright homepage works.
 */
test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});
