// Generated from ./CanopusDSL.g4 by ANTLR 4.13.2
/** biome-ignore-all lint/correctness/noUnusedFunctionParameters: autogenerated by ANTLR4 */
// jshint ignore: start
import antlr4 from "antlr4";

// This class defines a complete listener for a parse tree produced by CanopusDSLParser.
export default class CanopusDSLListener extends antlr4.tree.ParseTreeListener {
	// Enter a parse tree produced by CanopusDSLParser#program.
	enterProgram(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#program.
	exitProgram(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#patternDef.
	enterPatternDef(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#patternDef.
	exitPatternDef(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#patternExpr.
	enterPatternExpr(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#patternExpr.
	exitPatternExpr(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#middleExpr.
	enterMiddleExpr(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#middleExpr.
	exitMiddleExpr(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#multipExpr.
	enterMultipExpr(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#multipExpr.
	exitMultipExpr(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#alternativeExpr.
	enterAlternativeExpr(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#alternativeExpr.
	exitAlternativeExpr(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#elementExpr.
	enterElementExpr(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#elementExpr.
	exitElementExpr(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#id.
	enterId(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#id.
	exitId(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#wildcard.
	enterWildcard(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#wildcard.
	exitWildcard(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#multipOperator.
	enterMultipOperator(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#multipOperator.
	exitMultipOperator(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#expr.
	enterExpr(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#expr.
	exitExpr(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#condition.
	enterCondition(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#condition.
	exitCondition(ctx) {}

	// Enter a parse tree produced by CanopusDSLParser#comparator.
	enterComparator(ctx) {}

	// Exit a parse tree produced by CanopusDSLParser#comparator.
	exitComparator(ctx) {}
}
