FROM node:22-alpine

WORKDIR /app

COPY yarn.lock package.json

COPY src/ ./src/

COPY index.html .

COPY public/ ./public/

COPY *.json .

COPY *.js .

COPY *.ts .

RUN yarn install

COPY .env.production .

RUN yarn build

CMD ["yarn", "preview", "--host"]
