FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN --mount=type=cache,target=/root/.cache/yarn \
    yarn install --frozen-lockfile

COPY . .

ARG VITE_API_HOST
ARG VITE_API_PORT
ARG VITE_INTERFACE_MODE=full
ARG VITE_GOOGLE_CLIENT_ID

RUN yarn build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
